### ISSUE TITLE
路径绘制问题

### ISSUE THREAD

**Issue by zachaxy** [NoEndToLF/ChinaMapView#1]
请问 MyMapView 在放大或者移动的情况 下, 在 onDraw 方法中,重新绘制各个省份的时候,为什么直接 drawPath 就适配了当前的放大或者移动,而不用改变各个省份的 path 中的数据?

**Comment by aiceking** [comment]
因为缩放和平移是基于整个画布的，即Canvas,画布大了，上面的内容也就大了，所以不需要改变各省份的path中的数据，只需要改变一次，就是最开始为了适应手机宽度，其他时候就交给画布就行了，最后，只需要换算出缩放平移后的点击的坐标相对于Map的坐标，就可以知道点击了那个省份

**Comment by aiceking** [comment]
当然，缩放和平移也可以通过改变Path来做，我也踩过这个坑，缩放平移过程中说实话，绘制速度远远赶不上操作速度，会造成卡顿，因此放弃这种做法
