### ISSUE TITLE
请问能否在地图里显示省份名称？

### ISSUE THREAD

**Issue by Moyck** [NoEndToLF/ChinaMapView#4]
请问能否在地图里显示省份名称？

**Comment by aiceking** [comment]
> 请问能否在地图里显示省份名称？

这个需求很简单，但是得在svg文件里标记出省份中心的位置，来显示省份名称，当然在现有资源下也能实现，但是要自己算中心点位置，简单思路来说就是找到省份path的上下左右边界点，然后各取一半就是中心点位置，这个需求我之后会实现

**Comment by whe0804** [comment]
这个需求加上没呀?

**Comment by aiceking** [comment]
> 这个需求加上没呀?

已更新，1.0.2

**Comment by aiceking** [comment]
> 请问能否在地图里显示省份名称？

已更新，1.0.2
