### ISSUE TITLE
不断打印日志问题

### ISSUE THREAD

**Issue by rcj60560** [NoEndToLF/ChinaMapView#7]
map.setOnProvinceClickLisener(new ChinaMapView.onProvinceClickLisener() {
            @Override
            public void onSelectProvince(String provinceName) {
                Log.i(TAG, "onSelectProvince: -------->>>>>>>>>>>>>>>>>>:");
                for (ProvinceModel provinceModel : provincesList) {
                    String name = provinceModel.getName();
                    if (name.equals(provinceName)) {
                        provinceModel.setColor(yellow);
                    }else {
                        provinceModel.setColor(grey);
                    }
                    Log.i(TAG, "onSelectProvince: " + name + ",, thread:" + Thread.currentThread().getName());
                }
                mapView.notifyDataChanged();
            }
        });
你好，
这段代码能实现点击的省份切换成我想要的颜色 但是log日志不停的打印 这是为啥 @NoEndToLF

**Comment by aiceking** [comment]
> map.setOnProvinceClickLisener(new ChinaMapView.onProvinceClickLisener() { @OverRide public void onSelectProvince(String provinceName) { Log.i(TAG, "onSelectProvince: -------->>>>>>>>>>>>>>>>>>:"); for (ProvinceModel provinceModel : provincesList) { String name = provinceModel.getName(); if (name.equals(provinceName)) { provinceModel.setColor(yellow); }else { provinceModel.setColor(grey); } Log.i(TAG, "onSelectProvince: " + name + ",, thread:" + Thread.currentThread().getName()); } mapView.notifyDataChanged(); } }); 你好， 这段代码能实现点击的省份切换成我想要的颜色 但是log日志不停的打印 这是为啥 @NoEndToLF

下个版本删除掉

**Comment by rcj60560** [comment]
@aiceking 多谢

**Comment by aiceking** [comment]
> @aiceking 多谢

我刚看了一下，日志是你自己打印的

**Comment by aiceking** [comment]
> @aiceking 多谢
Log.i(TAG, "onSelectProvince: -------->>>>>>>>>>>>>>>>>>:");
Log.i(TAG, "onSelectProvince: " + name + ",, thread:" + Thread.currentThread().getName());
